openapi: 3.0.0
info:
  version: "1.0.0"
  title: Arsenal Players API
  description: "API to fetch the list of Arsenal Football Club players."
servers:
  - url: "http://localhost/"
    description: "Local server for testing"

paths:
  /arsenal/players:
    get:
      tags:
        - players
      summary: "Fetch the list of Arsenal players"
      description: "Retrieves the list of current players in the Arsenal Football Club."
      responses:
        200:
          description: A list of players
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PlayersList'
        404:
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Resource not found"

components:
  schemas:
    PlayersList:
      type: object
      properties:
        team:
          type: string
          example: "Arsenal"
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'

    Player:
      type: object
      properties:
        name:
          type: string
          example: "ブカヨ・サカ"
        position:
          type: string
          example: "フォワード"
        number:
          type: integer
          example: 7
       
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
